[package]
name = "pebble-rust"
version = "0.1.0"
authors = ["RoccoDev <hey@rocco.dev>"]
edition = "2018"
license = "GPL-3.0-or-later AND BSD-3-Clause"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]